name: Build and Test Source Code

on:
  push:
    branches: [ '**' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Start PubSub Emulator
      run: docker-compose -f "./test/e2e_test/docker-compose.yaml" up

    - name: Test
      run: go test -v ./...

    - name: Clean up
      if: always()
      run: docker-compose -f "./test/e2e_test/docker-compose.yaml" down
